// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usdhemikpmbcuwearsob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZGhlbWlrcG1iY3V3ZWFyc29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTg1MDcsImV4cCI6MjA2Nzk3NDUwN30.8cnuHbusw7XWs__Uv0C-VBlrXRdpQjuV-Z7FxrzpA64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});